language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
install:
  - pip install tox-travis codecov flake8
script:
  - flake8
  - tox
after_success:
  - codecov
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: algosec
  password:
    secure: LVxqWJXJTa5YCM5wDKkEEySKcFlGnTF3j+4qMIY7/vWbPpdfGv/C6ZokqZ3h6uTrB6c2wagoBJGbf7vxWeNdIb3wcEhhUlvEDpP8/r2P09iMWfO6g76/qxKS9NfLETE1Pf41PGYV7ojuSFJKu+Ni50F/XSZyb+Eowb4b1AUccBO9N0RzdkU5bBD2yQG/6K1IWUvZYpae+I3vNGVixwRuJnGCJ18wwsRwi0Xq/hdwEeAigisGmX4u2IwCp+23EKMOWerBOJBKdL+RwbNmSZSCXHII3YZY1isQURlFv292n01h6fyXcDMzZiLOe8YbqOIQJxKiVFB/IaFgFobKxH6b32jPfBvyip3U/gLbnT4Q0QSuHGRKI803RE0PKK7f8f6Tg6kL+qva37B0E46k8RNbqj6p4RMIh7Pz8di1LL+xnIwn5X3Cx14P1WaxeStmwdeBxOTlelR6RXa1YiB+3fg1xCN9qadQgpNScN/M0XvDGLgXiNiMvRp8PHkfuqDOJNPNt3VH4Zw1rjfkKYhiEoJMgwNf9b6y8rumjzjRtiYL//2dH0RYWI3ZuReiFjDsA8wLtf7Xh/pfHLfIdkZ6rHKLHUb8LeCluCIp+MEuHVdBihKr0/2GEtSKrqFkM66WPSfTSzGrw/2Td2vqg/fr1rwryHTQJkbgtVWeQ1rmqsj3VmA=
  on:
    tags: true
    repo: algosec/algosec-resilient
    python: 3.6
