language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
install:
  - pip install tox-travis codecov flake8
script:
  - flake8
  - tox
after_success:
  - codecov
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: algosec
  password:
    secure: rtdgMS6yYQMi686vVBx6Iu4wsi/lr+l8zGUCQriNcJRzaoibbP03/oPytuUfv6I7iFdDqyCzA5p+0iMfdSTGAd1MJdg+COhlVMOw1G4bnl+XTxILGGSeufgFZiszMVjt34X4zhAVv77DObuXqUJ13wMCsbsJRkpokJUqy+FQyhIIHisRohY5wBW2naFVZc9VvRUWfxMl0uQ/ra0vrNHfXxBV3pK1ym4A1hJwQKHy/0NQNNLA8YDiaD9UMrHpBEF4/UqOCiFu40jRE5Bu3d3a54ni0GIv4RmUTBTYrVfTU87bZmxZL2Lypl69tSc1Z4Q3WUGjyJl8zS1zW9mb2pduGreW45ht5UfBF/zUS+Vbhn6vZH0Pyx8kEkSOcOIWpVTbAU+x/UQDB61I5C4vsDujdIn/kcW56MHz9ErLDqMax7mBVo07KqbaOJYsYwh2w4erw/jinYjF5g/Ac+J+9QI2OpvUdYB4vhX+Kh8V0hsr+SBBMDoXs/vO0oKRh7c6KSiR77x2NX5GfdTo1WoQSzKx2I3SMOuJ32lRUXDFbMc/u1Ij/tMmYDqiNCyvKuCG0R5oJl44OksXL3kSGdaBVoLLOc8gAdnSxmky4AGmjTXkPPC8tVPuKfG2NXs/+cjVad9cExOiFc5d4Z27d26EHt0gNLSOK+ib1+AQjr+9pwn9osk=
  on:
    tags: true
    repo: algosec/algosec-resilient
    python: 3.6
