language: python
python:
  - '2.7'
  - '3.5'
  - '3.6'
# command to install dependencies
install:
  - pip install tox-travis codecov flake8
# command to run tests
script:
  - flake8
  - tox
after_success:
  - codecov
notifications:
  email:
    on_success: never
    on_failure: always
